apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8002
  selector:
    app: order-service

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: gokumonkey/order-service:12
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
